(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var h="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};function k(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}
var l=k(this);function m(a,b){if(b)a:{var c=l;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&h(c,a,{configurable:!0,writable:!0,value:b})}}
var n="undefined"!=typeof navigator&&/Trident/.test(navigator.userAgent)?new function(){this.target=document.createElement("textarea")}:null;
function p(a,b,c){c=void 0===c?{}:c;this.g=a;this.onFrame=b;this.h=null;this.i=c.width||640;this.j=c.height||480;this.l=c.facingMode||"user";this.width=this.i;this.height=this.j;this.m=new VideoFrame({timestamp:0,duration:0});var d=this;this.g.addEventListener("loadeddata",function(){d.width=d.g.videoWidth;d.height=d.g.videoHeight;var e=d.g.videoWidth/d.g.videoHeight,f=d.i/d.j;1e-6>Math.abs(e-f)?d.h=null:(e=Math.max(d.i,d.j*e),f=Math.max(d.j,d.i/e),e={width:e,height:f,x:(d.i-e)/2,y:(d.j-f)/2},
d.h=e)},!1)}function q(a){window.requestAnimationFrame(function(){r(a)})}function r(a){if(a.g.paused||a.g.currentTime===a.m.timestamp)q(a);else{var b=a.g.currentTime;a.m=new VideoFrame({timestamp:b,duration:0});if(a.h){var c=document.createElement("canvas");c.width=a.i;c.height=a.j;var d=c.getContext("2d");d.drawImage(a.g,a.h.x,a.h.y,a.h.width,a.h.height);a.onFrame(c)}else a.onFrame(a.g);q(a)}}
p.prototype.start=function(){var a=this;return navigator.mediaDevices&&navigator.mediaDevices.getUserMedia||navigator.webkitGetUserMedia||navigator.mozGetUserMedia?navigator.mediaDevices.getUserMedia({video:{facingMode:this.l,width:this.i,height:this.j}}).then(function(b){a.g.srcObject=b;if(n){var c=n.target;c.select();try{document.execCommand("copy")}catch(d){console.log(d)}c.blur()}q(a)}).catch(function(b){console.error("Failed to acquire camera feed: "+b)}):Promise.reject(Error("Browser does not support getUserMedia."))};var t=["Camera"],u=l;t[0]in u||"undefined"==typeof u.execScript||u.execScript("var "+t[0]);for(var v;t.length&&(v=t.shift());)t.length||void 0===p?u[v]&&u[v]!==Object.prototype[v]?u=u[v]:u=u[v]={}:u[v]=p;})();
