(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var m="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};function n(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}
var p=n(this);function q(a,b){if(b)a:{var c=p;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&m(c,a,{configurable:!0,writable:!0,value:b})}}q("Symbol",function(a){if(a)return a;var b=function(f,g){this.g=f;m(this,"description",{configurable:!0,writable:!0,value:g})};b.prototype.toString=function(){return this.g};var c="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",d=0,e=function(f){if(this instanceof e)throw new TypeError("Symbol is not a constructor");return new b(c+(f||"")+"_"+d++,f)};return e});
q("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=p[b[c]];"function"==typeof d&&"function"!=typeof d.prototype[a]&&m(d.prototype,a,{configurable:!0,writable:!0,value:function(){return r(this)}})}return a});function r(a){var b=0;return t(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})}
function t(a){var b={next:a};b[Symbol.iterator]=function(){return this};return b}function u(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:r(a)}}
var v;if("function"==typeof Object.setPrototypeOf)v=Object.setPrototypeOf;else{var w;a:{var x={a:!0},y={};try{y.__proto__=x;w=y.a;break a}catch(a){}w=!1}v=w?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var z=v;function A(){this.j=!1;this.h=null;this.l=void 0;this.g=1;this.o=this.i=0;this.m=null}function B(a){if(a.j)throw new TypeError("Generator is already running");a.j=!0}A.prototype.s=function(a){this.l=a};
function C(a,b){a.m={v:b,u:!0};a.g=a.i||a.o}A.prototype.return=function(a){this.m={return:a};this.g=this.o};function D(a,b,c){a.g=c;return{value:b,done:!1}}function E(a,b,c){a.g=c;return{value:b,done:!0}}function F(a){this.g=new A;this.h=a}function G(a,b){B(a.g);var c=a.g.h;if(c)return H(a,c.call(null,b));c=a.g.g;if(a.g.h)return H(a,c);if(!c)return{value:void 0,done:!0};switch(c){case 1:if(b)return C(a.g,b),G(a);break;case 2:if(b){if(b.u)return E(a.g,b.v,3);C(a.g,b.v)}return D(a.g,a.g.l,4);
case 3:a.g.l=void 0;return E(a.g,a.g.m.return);case 4:var d=b;b=void 0;var e=u(d);d=e.next();if(!d.done){b=d.value;d=e.next();if(!d.done)throw Error("yield* cannot yield more than one item");}a.g.l=b;return E(a.g,a.g.l,3)}}
function H(a,b){a.g.j=!1;a.g.h=null;a.g.l=void 0;if(b.done){a.g.g=a.g.i||a.g.o;if(a.g.m){if(a.g.m.u)return E(a.g,a.g.m.v,3);var c=a.g.m.return;a.g.m=null;return E(a.g,c)}return E(a.g,void 0)}a.g.h=b;return D(a.g,a.g.l,2)}function I(a){this.g=new F(a)}I.prototype.next=function(a){return G(this.g,a)};function J(a){return new I(function(){return a})}
function K(a,b){var c=this;this.h=a;this.i=b;this.g=0;this.h.addEventListener("click",function(){c.g++;window.setTimeout(function(){1<c.g?c.i(null):1==c.g&&c.i(!1);c.g=0},250)})}function L(a,b){var c=this;this.g=a;this.l=b;this.j=this.i=0;this.h=new K(this.g,function(d){c.l({i:c.i,j:c.j,ctrlKey:d})});this.g.addEventListener("mousemove",function(d){c.i=d.offsetX;c.j=d.offsetY})}
function M(a,b,c){var d=this;this.g=a;this.o=c;this.i=b;this.j=!1;this.l=this.h=0;this.m=new K(this.g,function(e){d.j?d.j=!1:d.o({i:d.h,j:d.l,ctrlKey:e})});this.g.addEventListener("mousedown",function(e){d.j=!0;d.h=e.offsetX;d.l=e.offsetY;d.i({i:d.h,j:d.l,ctrlKey:!1})});this.g.addEventListener("mousemove",function(e){if(d.j){var f=e.offsetX-d.h,g=e.offsetY-d.l;d.h=e.offsetX;d.l=e.offsetY;d.i({i:f,j:g,ctrlKey:e.ctrlKey})}})}
function N(a){var b=window.location.search;if(b){var c=b.indexOf(a);if(-1!=c){var d=b.indexOf("&",c);return-1!=d?b.substring(c+a.length+1,d):b.substring(c+a.length+1)}}}
function O(a){var b=0;return J(function(){var c;return t(function(d){if(1==d.g)return c=b,E(d,b,2);if(2!=d.g)return b=a.next().value,D(d,b,1);d.g=1;return{value:c,done:!1}})})};var P=["ControlUtils"],Q=p;P[0]in Q||"undefined"==typeof Q.execScript||Q.execScript("var "+P[0]);for(var R;P.length&&(R=P.shift());)P.length||void 0===O?Q[R]&&Q[R]!==Object.prototype[R]?Q=Q[R]:Q=Q[R]={}:Q[R]=O;})();
