(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var k="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};function l(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}
var n=l(this);function p(a,b){if(b)a:{var c=n;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&k(c,a,{configurable:!0,writable:!0,value:b})}}
var q={color:"white",lineWidth:4,radius:6};function r(a){a=a||{};return Object.assign({},q,{color:a.color||q.color,lineWidth:a.lineWidth||q.lineWidth,radius:a.radius||q.radius})}function t(a,b){return a instanceof Function?a(b):a}function u(a,b,c){return Math.max(Math.min(a,c),b)}function v(a){return.5>a?2*a:2*(1-a)}function w(a){return-2*a+2}
function x(a,b,c){c=r(c);var d=c.lineWidth,e=c.radius,f=c.color;if(void 0!==b){var h=Math.PI;b=u(b,0,1);var g=a.canvas.getContext("2d");g.save();var m=g.canvas.width;c=g.canvas.height;d=t(d,b);e=t(e,b);f=t(f,b);g.translate(m/2,c/2);g.beginPath();g.lineWidth=d;g.strokeStyle=f;g.arc(0,0,Math.max(e-d/2,0),0,2*h);g.stroke();g.restore()}}
function y(a,b,c){c=r(c);var d=c.lineWidth,e=c.color;if(void 0!==b){b=u(b,0,1);var f=a.canvas.getContext("2d");f.save();var h=f.canvas.width,g=f.canvas.height;d=t(d,b);e=t(e,b);f.translate(h/2,g/2);f.beginPath();f.lineWidth=d;f.strokeStyle=e;f.moveTo(0,-15);f.lineTo(0,-15-150*b);f.stroke();f.restore()}}
function z(a,b,c){c=r(c);var d=c.color,e=c.lineWidth,f=c.radius;if(a&&b&&b.length){c=a.canvas.getContext("2d");c.save();for(var h=0;h<b.length;++h){var g=b[h];if(g&&void 0!==g.visibility&&!(.5>g.visibility)){var m=g.x*a.canvas.width;g=g.y*a.canvas.height;var D=t(e,h),E=t(f,h),A=t(d,h);c.fillStyle=A;c.strokeStyle=A;c.lineWidth=D;c.beginPath();c.arc(m,g,E,0,2*Math.PI);c.fill()}}c.restore()}}
function B(a,b,c,d){d=r(d);var e=d.color,f=d.lineWidth,h=d.radius;if(a&&b&&c){var g=a.canvas.getContext("2d");g.save();for(var m=0;m<c.length;++m){var D=c[m],E=b[D[0]],A=b[D[1]];if(E&&A&&!(void 0!==E.visibility&&.5>E.visibility||void 0!==A.visibility&&.5>A.visibility)){var F=E.x*a.canvas.width,G=E.y*a.canvas.height;E=A.x*a.canvas.width;A=A.y*a.canvas.height;g.lineWidth=t(f,m);g.strokeStyle=t(e,m);g.beginPath();g.moveTo(F,G);g.lineTo(E,A);g.stroke()}}g.restore();if(h)for(m=0;m<b.length;++m)E=b[m],
E&&void 0!==E.visibility&&!(.5>E.visibility)&&(F=E.x*a.canvas.width,G=E.y*a.canvas.height,g.fillStyle=t(e,m),g.beginPath(),g.arc(F,G,t(h,m),0,2*Math.PI),g.fill())}}
function C(a,b,c,d){d=r(d);var e=d.color,f=d.lineWidth;d=d.radius;if(a&&b&&c){var h=a.canvas.getContext("2d");h.save();for(var g=0;g<c.length;++g){var m=c[g];h.lineWidth=t(f,g);h.strokeStyle=t(e,g);h.beginPath();for(var D=0;D<m.length;++D){var E=b[m[D]];E&&void 0!==E.visibility&&!(.5>E.visibility)&&(E=E.x*a.canvas.width,F=b[m[D]].y*a.canvas.height,0==D?h.moveTo(E,F):h.lineTo(E,F))}h.stroke()}h.restore();if(d)for(g=0;g<b.length;++g)m=b[g],m&&void 0!==m.visibility&&!(.5>m.visibility)&&(E=m.x*a.canvas.width,
F=m.y*a.canvas.height,h.fillStyle=t(e,g),h.beginPath(),h.arc(E,F,t(d,g),0,2*Math.PI),h.fill())}}var H={drawCenterProgress:x,drawRectangle:function(a,b,c){c=r(c);var d=c.lineWidth,e=c.color,f=c.radius;if(void 0!==b){var h=a.canvas.getContext("2d");h.save();var g=h.canvas.width;a=h.canvas.height;d=t(d,0);f=t(f,0);e=t(e,0);h.translate(g/2,a/2);b=b.g;g=-(b.width-f*v(b.xScale))/2;a=-(b.height-f*v(b.yScale))/2;b=b.width-f*v(b.xScale);var m=b.height-f*v(b.yScale);h.beginPath();h.lineWidth=d;h.strokeStyle=e;h.rect(g,a,b,m);h.stroke();h.restore()}},drawConnectors:B,drawLandmarks:z,
drawPackedSawtooth:y,drawRoundRectangle:function(a,b,c){c=r(c);var d=c.lineWidth,e=c.color,f=c.radius;if(void 0!==b){var h=a.canvas.getContext("2d");h.save();var g=h.canvas.width;a=h.canvas.height;d=t(d,0);f=t(f,0);e=t(e,0);h.translate(g/2,a/2);b=b.g;g=-(b.width-f*w(b.xScale))/2;a=-(b.height-f*w(b.yScale))/2;b=b.width-f*w(b.xScale);var m=b.height-f*w(b.yScale);h.beginPath();h.lineWidth=d;h.strokeStyle=e;h.roundRect(g,a,b,m,f);h.stroke();h.restore()}},lerp:u};var I=n;p("drawCenterProgress",x);
p("drawConnectors",B);p("drawLandmarks",z);p("drawPackedSawtooth",y);p("drawRectangle",H.drawRectangle);p("drawRoundRectangle",H.drawRoundRectangle);p("lerp",u);var J=["DrawingUtils"],K=I;J[0]in K||"undefined"==typeof K.execScript||K.execScript("var "+J[0]);for(var L;J.length&&(L=J.shift());)J.length||void 0===H?K[L]&&K[L]!==Object.prototype[L]?K=K[L]:K=K[L]={}:K[L]=H;})();
